const { TAG_TAXONOMY, extractCandidateTagsHeuristic } = require('./tagSystem');

const TAG_EXTRACTION_CONFIG = {
  model: process.env.TAG_EXTRACTION_MODEL || 'Qwen2.5-7B-Instruct',
  serviceUrl: process.env.TAG_EXTRACTION_SERVICE_URL || 'http://localhost:8002',
  enabled: process.env.TAG_EXTRACTION_ENABLED === 'true'
};

const getTagExtractionStatus = () => ({ ...TAG_EXTRACTION_CONFIG });

const extractCandidateTagsForProduct = async (product) => {
  if (!TAG_EXTRACTION_CONFIG.enabled) {
    return {
      modelReady: false,
      source: 'heuristic-fallback',
      model: TAG_EXTRACTION_CONFIG.model,
      tags: extractCandidateTagsHeuristic(product),
      note: 'Qwen model slot is reserved. Enable TAG_EXTRACTION_ENABLED=true after model service is ready.'
    };
  }

  try {
    const response = await fetch(`${TAG_EXTRACTION_CONFIG.serviceUrl}/extract-tags`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: TAG_EXTRACTION_CONFIG.model,
        title: product.name,
        text: product.description,
        existingTags: product.tags || [],
        allowedTaxonomy: TAG_TAXONOMY
      })
    });

    if (!response.ok) {
      return {
        modelReady: false,
        source: 'heuristic-fallback',
        model: TAG_EXTRACTION_CONFIG.model,
        tags: extractCandidateTagsHeuristic(product),
        note: `Qwen service responded ${response.status}. Fallback applied.`
      };
    }

    const data = await response.json();
    return {
      modelReady: true,
      source: 'qwen2.5-7b-instruct',
      model: TAG_EXTRACTION_CONFIG.model,
      tags: data.tags || [],
      note: 'Candidate tags generated by Qwen model. Please validate with whitelist before writing to DB.'
    };
  } catch (error) {
    return {
      modelReady: false,
      source: 'heuristic-fallback',
      model: TAG_EXTRACTION_CONFIG.model,
      tags: extractCandidateTagsHeuristic(product),
      note: `Qwen service unavailable: ${error.message}. Fallback applied.`
    };
  }
};

module.exports = {
  getTagExtractionStatus,
  extractCandidateTagsForProduct
};
